### ISSUE TITLE
Shenanagins going on with install.py

### ISSUE THREAD

**Issue by ethanjohnstone** [ethanjohnstone/genesis#3] opened 2019-03-25 07:34 UTC
# Bing

After a fresh install and running `python3 install.py`  , I can only get as far as providing the answer to
*# Grab all necessary data* after the final one it throws an error with the following stack trace.
```
Traceback (most recent call last):
  File "install.py", line 95, in <module>
    replace_in_file (filename=file, text=text, replacement_text=value)
  File "install.py", line 50, in replace_in_file
    for line in lines:
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/fileinput.py", line 252, in __next__
    line = self._readline()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/fileinput.py", line 366, in _readline
    return self._readline()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 5: invalid start byte
```

**Comment by NikxDa** [comment] 2019-03-29 06:09
Issue was caused by an `.exe` file in a `node_modules` folder that should not have existed. Closing this.

**Closed** 2019-03-29 06:09 UTC
